# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54beef282ced4303eb3887d058861be591886d86a11ca0c31754143e2cb86ee581f137389093d8df58fd7fd90069697c4530f8d071ae8753926b4e45cfebb48c

test:
  secret_key_base: dcbd13122f758002d7c4b61de856b7d7e0549620c526cdeebcaabf1a6984a0aa2100bc9bc4320bc74a91d5fc787b223bb1a496115d16545b4de0bd1d29a42750

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
